name: cicd-workflow

on:
  push: 
    branches: [feature]
    paths:
      - 'server/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login Dockerhub
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: abcd15523/pharmcode:latest
  
  deploy:
    needs: build
    runs-on: ubuntu-latest 
    steps:
      - name: deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST_DNS }}
          username: ${{ secrets.AWS_EC2_USERNAME }}
          key: ${{ secrets.AWS_PRIVATE_KEY }}
          script: |
            docker pull abcd15523/pharmcode:latest
            docker stop myapp || true
            docker rm myapp || true
            docker run -d --name myapp --restart unless-stopped --env-file /pharm-code/server.env -p 3000:3000 abcd15523/pharmcode:latest

